---
- name: install phpldap
  apt: name=phpldapadmin state=present 

- name: install phpldap config file
  template: src=config.php dest=/etc/phpldapadmin/config.php  mode=0644

- name: install phpldap.conf in sites-enabled of apache2
  template: src=phpldap.conf dest=/etc/apache2/sites-enabled/phpldap.conf mode=0644

#- name: restart apache2
#  shell: service apache2 restart

