---

- include: init.yml
  

#- hosts: all
#  tasks:
#     - name: stop filebeat
#       service: name=filebeat state=stopped 
#       tags: stop-filebeat

- hosts: elasticsearch,kibana
  vars_files: 
    - secrets/{{ site }}-secrets.yml
  roles:
    - {role: elasticsearch , tags: [elk, elasticsearch], 
        es_cluster_name: "phenix-elk", 
        elasticsearch_version: 2.4.0,
        es_heap_size: "31g",
        es_refresh_interval: "1s",
        es_clients: "{{ groups['kibana'] }}",
        index_mapper_dynamic: true }
    
- hosts: kibana
  vars_files:
    - secrets/{{ site }}-secrets.yml
  roles:
    - {role: kibana , tags: [elk, kibana], es_host: '{{ inventory_hostname }}:{{ es_api_port }}'}

- hosts: logstash
  vars_files:
    - secrets/{{ site }}-secrets.yml
  roles:
    - {role: logstash , tags: [elk, logstash]}

- hosts: all
  vars_files:
    - secrets/{{ site }}-secrets.yml
  roles:
    - {role: filebeat , tags: [elk, filebeat]}
    - {role: collectd , tags: [collectd]}
#    - {role: elastalert , tags: [elastalert]}



