---
- name: Wait for elasticsearch to launch services
  wait_for:  port={{ item }} delay=5 timeout=60
  with_items:
     - "{{ es_api_port }}"
     - "{{ es_transport_port }}"

- name: check cluster status
  shell: "sleep 10; curl --silent -u 'admin:{{ vault_ldap_admin_pw }}' -X GET http://{{ play_hosts[0] }}:{{ es_api_port }}/_cat/health"
  register: cluster_status
  failed_when: '"red" in cluster_status.stdout'
  run_once: true
