---
# LogRotate Setup
- name: Ensure logrotate present
  apt: name=logrotate state=present update_cache=yes
# when: logrotate_set is defined and logrotate_set|length > 0

- name: Configure logrotate.d script
  template: src=logr_template.j2 dest="{{ logrotate_conf_dir }}{{ item.name }}"
  with_items: "{{ logrotate_set }}"
  when: logrotate_set is defined

- name: Apply New logrotate Now
  shell: logrotate -f "{{ logrotate_conf_dir }}{{ item.name }}"
  with_items: "{{ logrotate_set }}"
  when: logrotate_set is defined
