#
# parameters: plugin_name, plugin_version
#

- name: check kibana plugins
  command: /opt/kibana/bin/kibana plugin --list
  register: installed_plugins

- block:
  - name: Stop kibana service 
    service: name=kibana state=stopped
  - name: install {{ plugin_name }} plugin
    environment: { NODE_TLS_REJECT_UNAUTHORIZED: 0 }
    command: /opt/kibana/bin/kibana plugin --install {{ plugin_name }} --url {{ kibana_repository_plugins }}{{ plugin_name }}-{{ plugin_version }}.zip 
  when: plugin_version != "" and "{{ plugin_name }}" not in installed_plugins.stdout

- block:
  - name: Stop kibana service
    service: name=elasticsearch state=stopped
  - name: remove {{ plugin_name }} plugin
    command: /opt/kibana/bin/kibana plugin --remove {{ plugin_name }}
  when: plugin_version == "" and "{{ plugin_name }}" in installed_plugins.stdout
