- name: install pip
  apt: name=python-pip state=present

#- name: install elastalert
#  pip: name=elastalert state=present


- unarchive:
    src: "{{ home }}elastalert.tar"
    dest: /opt
    remote_src: True

- name: Install virtualenv
  pip:
    name: file:///opt/elastalert/offline/virtualenv-15.1.0-py2.py3-none-any.whl

- name: Avoid errors that result from InsecurePlatformWarning
  apt:
    name: "{{ item }}"
  with_items:
    - python-dev
    - libffi-dev
    - libssl-dev
  tags:
    - apt

#Install dependencies

- name: Install six 1.10.0
  pip:
    name: file:///opt/elastalert/offline/six-1.10.0-py2.py3-none-any.whl
    virtualenv: /opt/elastalert/venv

- name: Install urllib3-1.22
  pip:
    name: file:///opt/elastalert/offline/urllib3-1.22-py2.py3-none-any.whl
    virtualenv: /opt/elastalert/venv

- name: Install oauthlib-2.0.2.tar.gz
  pip:
    name: file:///opt/elastalert/offline/oauthlib-2.0.2.tar.gz
    virtualenv: /opt/elastalert/venv

- name: Install defusedxml-0.5.0-py2.py3-none-any.whl
  pip:
    name: file:///opt/elastalert/offline/defusedxml-0.5.0-py2.py3-none-any.whl
    virtualenv: /opt/elastalert/venv

- name: Install chardet-3.0.4-py2.py3-none-any.whl
  pip:
    name: file:///opt/elastalert/offline/chardet-3.0.4-py2.py3-none-any.whl
    virtualenv: /opt/elastalert/venv

- name: Install python-dateutil>=2.6.0
  pip:
    name: file:///opt/elastalert/offline/python_dateutil-2.6.1-py2.py3-none-any.whl
    virtualenv: /opt/elastalert/venv

- name: Install docutils-0.14-py2-none-any.whl
  pip:
    name: file:///opt/elastalert/offline/docutils-0.14-py2-none-any.whl
    virtualenv: /opt/elastalert/venv

- name: Install jmespath-0.9.3-py2.py3-none-any.whl
  pip:
    name: file:///opt/elastalert/offline/jmespath-0.9.3-py2.py3-none-any.whl
    virtualenv: /opt/elastalert/venv

- name: Install idna-2.6-py2.py3-none-any.whl
  pip:
    name: file:///opt/elastalert/offline/idna-2.6-py2.py3-none-any.whl
    virtualenv: /opt/elastalert/venv

- name: Install certifi-2017.7.27.1-py2.py3-none-any.whl
  pip:
    name: file:///opt/elastalert/offline/certifi-2017.7.27.1-py2.py3-none-any.whl
    virtualenv: /opt/elastalert/venv


- name: Install requests-2.18.4-py2.py3-none-any.whl
  pip:
    name: file:///opt/elastalert/offline/requests-2.18.4-py2.py3-none-any.whl
    virtualenv: /opt/elastalert/venv

- name: Install requests_toolbelt-0.8.0-py2.py3-none-any.whl
  pip:
    name: file:///opt/elastalert/offline/requests_toolbelt-0.8.0-py2.py3-none-any.whl
    virtualenv: /opt/elastalert/venv

- name: Install botocore-1.7.2-py2.py3-none-any.whl
  pip:
    name: file:///opt/elastalert/offline/botocore-1.7.2-py2.py3-none-any.whl
    virtualenv: /opt/elastalert/venv

- name: Install requests_oauthlib-0.8.0-py2.py3-none-any.whl
  pip:
    name: file:///opt/elastalert/offline/requests_oauthlib-0.8.0-py2.py3-none-any.whl
    virtualenv: /opt/elastalert/venv

- name: Install setuptools-36.3.0-py2.py3-none-any.whl
  pip:
    name: file:///opt/elastalert/offline/setuptools-36.3.0-py2.py3-none-any.whl
    virtualenv: /opt/elastalert/venv

- name: Install futures-3.1.1.tar.gz
  pip:
    name: file:///opt/elastalert/offline/futures-3.1.1.tar.gz
    virtualenv: /opt/elastalert/venv

- name: Install s3transfer-0.1.11-py2.py3-none-any.whl
  pip:
    name: file:///opt/elastalert/offline/s3transfer-0.1.11-py2.py3-none-any.whl
    virtualenv: /opt/elastalert/venv

- name: Install pytz-2017.2-py2.py3-none-any.whl
  pip:
    name: file:///opt/elastalert/offline/pytz-2017.2-py2.py3-none-any.whl
    virtualenv: /opt/elastalert/venv

- name: Install PySocks-1.5.6.tar.gz
  pip:
    name: file:///opt/elastalert/offline/PySocks-1.5.6.tar.gz
    virtualenv: /opt/elastalert/venv

- name: Install PyJWT-1.5.2-py2.py3-none-any.whl
  pip:
    name: file:///opt/elastalert/offline/PyJWT-1.5.2-py2.py3-none-any.whl
    virtualenv: /opt/elastalert/venv

- name: Install pbr-3.1.1-py2.py3-none-any.whl
  pip:
    name: file:///opt/elastalert/offline/pbr-3.1.1-py2.py3-none-any.whl
    virtualenv: /opt/elastalert/venv


- name: Install httplib2-0.10.3.tar.gz
  pip:
    name: file:///opt/elastalert/offline/httplib2-0.10.3.tar.gz
    virtualenv: /opt/elastalert/venv

- name: Install envparse-0.2.0.tar.gz
  pip:
    name: file:///opt/elastalert/offline/envparse-0.2.0.tar.gz
    virtualenv: /opt/elastalert/venv

- name: Install aws-requests
  pip:
    name: file:///opt/elastalert/offline/aws-requests-auth-0.3.3.tar.gz
    virtualenv: /opt/elastalert/venv

- name: Install blist>=1.3.6
  pip:
    name: file:///opt/elastalert/offline/blist-1.3.6.tar.gz
    virtualenv: /opt/elastalert/venv

- name: Install boto3>=1.4.4
  pip:
    name: file:///opt/elastalert/offline/boto3-1.4.7-py2.py3-none-any.whl
    virtualenv: /opt/elastalert/venv

- name: Install configparser>=3.5.0
  pip:
    name: file:///opt/elastalert/offline/configparser-3.5.0.tar.gz
    virtualenv: /opt/elastalert/venv

- name: Install croniter>=0.3.16
  pip:
    name: file:///opt/elastalert/offline/croniter-0.3.19.tar.gz
    virtualenv: /opt/elastalert/venv

- name: Install elasticsearch
  pip:
    name: file:///opt/elastalert/offline/elasticsearch-5.4.0-py2.py3-none-any.whl
    virtualenv: /opt/elastalert/venv

- name: Install exotel>=0.1.3
  pip:
    name: file:///opt/elastalert/offline/exotel-0.1.5.tar.gz
    virtualenv: /opt/elastalert/venv

- name: Install PyYAML>=3.12
  pip:
    name: file:///opt/elastalert/offline/PyYAML-3.12.tar.gz
    virtualenv: /opt/elastalert/venv

- name: Install simplejson>=3.10.0
  pip:
    name: file:///opt/elastalert/offline/simplejson-3.11.1.tar.gz
    virtualenv: /opt/elastalert/venv

- name: Install PyStaticConfiguration>=0.10.3
  pip:
    name: file:///opt/elastalert/offline/PyStaticConfiguration-0.10.3.tar.gz
    virtualenv: /opt/elastalert/venv


- name: Install stomp.py>=4.1.17
  pip:
    name: file:///opt/elastalert/offline/stomp.py-4.1.18.tar.gz
    virtualenv: /opt/elastalert/venv

- name: Install texttable>=0.8.8
  pip:
    name: file:///opt/elastalert/offline/texttable-0.9.1.tar.gz
    virtualenv: /opt/elastalert/venv

- name: Install ordereddict
  pip:
    name: file:///opt/elastalert/offline/ordereddict-1.1.tar.gz
    virtualenv: /opt/elastalert/venv

- name: Install functools32
  pip:
    name: file:///opt/elastalert/offline/functools32-3.2.3-2.tar.gz
    virtualenv: /opt/elastalert/venv

- name: Install funcsigs-1.0.2-py2.py3-none-any.whl
  pip:
    name: file:///opt/elastalert/offline/funcsigs-1.0.2-py2.py3-none-any.whl
    virtualenv: /opt/elastalert/venv

- name: Install pyasn1-0.3.3-py2.py3-none-any.whl
  pip:
    name: file:///opt/elastalert/offline/pyasn1-0.3.3-py2.py3-none-any.whl
    virtualenv: /opt/elastalert/venv

- name: Install enum34-1.1.6-py2-none-any.whl
  pip:
    name: file:///opt/elastalert/offline/enum34-1.1.6-py2-none-any.whl
    virtualenv: /opt/elastalert/venv

- name: Install ipaddress-1.0.18-py2-none-any.whl
  pip:
    name: file:///opt/elastalert/offline/ipaddress-1.0.18-py2-none-any.whl
    virtualenv: /opt/elastalert/venv

- name: Install pycparser-2.18.tar.gz
  pip:
    name: file:///opt/elastalert/offline/pycparser-2.18.tar.gz
    virtualenv: /opt/elastalert/venv


- name: Install cffi-1.10.0.tar.gz
  pip:
    name: file:///opt/elastalert/offline/cffi-1.10.0.tar.gz
    virtualenv: /opt/elastalert/venv

- name: Install asn1crypto-0.22.0-py2.py3-none-any.whl
  pip:
    name: file:///opt/elastalert/offline/asn1crypto-0.22.0-py2.py3-none-any.whl
    virtualenv: /opt/elastalert/venv

- name: Install cryptography-2.0.3.tar.gz
  pip:
    name: file:///opt/elastalert/offline/cryptography-2.0.3.tar.gz
    virtualenv: /opt/elastalert/venv

- name: Install mock>=2.0.0
  pip:
    name: file:///opt/elastalert/offline/mock-2.0.0-py2.py3-none-any.whl
    virtualenv: /opt/elastalert/venv

- name: Install pyOpenSSL-17.2.0-py2.py3-none-any.whl
  pip:
    name: file:///opt/elastalert/offline/pyOpenSSL-17.2.0-py2.py3-none-any.whl
    virtualenv: /opt/elastalert/venv

- name: Install twilio==6.0.0
  pip:
    name: file:///opt/elastalert/offline/twilio-6.0.0.tar.gz
    virtualenv: /opt/elastalert/venv

- name: Install jsonschema>=2.6.0
  pip:
    name: file:///opt/elastalert/offline/jsonschema-2.6.0-py2.py3-none-any.whl
    virtualenv: /opt/elastalert/venv

- name: Install jira>=1.0.10
  pip:
    name: file:///opt/elastalert/offline/jira-1.0.10-py2.py3-none-any.whl
    virtualenv: /opt/elastalert/venv


- name: Install elastalert
  command: /opt/elastalert/venv/bin/python setup.py install
  args:
    chdir: /opt/elastalert

- name: Flush handlers to ensure a local elasticsearch has been started
  meta: flush_handlers

- name: Install httplib2
  pip:
    name: file:///opt/elastalert/offline/httplib2-0.10.3.tar.gz

- name: Install elastalert-0.1.20.tar.gz
  pip:
    name: file:///opt/elastalert/offline/elastalert-0.1.20.tar.gz
    virtualenv: /opt/elastalert/venv

- name: remove proxy
  shell: sudo rm /etc/environment

- name: put the variable hhtp_proxy on NONE
  shell: http_proxy=""

- name: put the variable hhtps_proxy on NONE
  shell: https_proxy=""


- name: Check existence of elastalert metadata index
  uri:
    url: "http://{{ elastalert_elasticsearch_host }}:{{ elastalert_elasticsearch_port }}/{{ elastalert_index }}"
    method: HEAD
    status_code:
      - 200
      - 404
  register: elastalert_index_check

- name: Create elasticsearch index for elastalert metadata
  command: /opt/elastalert/venv/bin/elastalert-create-index --host "{{ elastalert_elasticsearch_host }}" --port "{{ elastalert_elasticsearch_port }}" --no-auth --no-ssl --url-prefix "" --index "{{ elastalert_index }}" --old-index ""
  args:
    chdir: /opt/elastalert
  when: elastalert_index_check.status == 404
  notify:
   - restart elastalert

- name: Add elastalert group
  group:
    name: elastalert
    state: present

- name: Add elastalert user
  user:
    name: elastalert
    group: elastalert
    system: yes
    state: present

- name: Create rules directory
  file:
    path: /etc/elastalert/rules
    state: directory
    owner: root
    group: root
    mode: 0755
  notify:
    - restart elastalert

- name: Process config template
  template:
    src: config.yaml
    dest: /etc/elastalert/config.yaml

- name: config rules
  copy: src=templates/rules.yml.j2  dest=/opt/elastalert/example_rules/new_rule.yml  mode=0644


- name: Enable elastalert at boot
  service:
    name: elastalert
    enabled: yes
  notify:
    - restart elastalert
