---
- name: Create kibana group
  group: name=kibana state=present

- name: Create user in kibana group
  user: name=kibana group=kibana shell=/bin/bash

- name: install kibana
  apt: deb={{ kibana_repository_plugins }}kibana-{{ kibana_version }}-amd64.deb state=present 
  notify: Restart kibana
#- name: install kibana
#  yum_phenix: name=kibana-{{ kibana_version }} state=present update_cache=yes

#- include: plugin.yml
#     plugin_name=license
#     plugin_version={% if license_version is defined %}{{ license_version }}{% endif %}

- include: plugin.yml
     plugin_name=marvel
     plugin_version={% if marvel_version is defined %}{{ marvel_version }}{% endif %}

- include: plugin.yml
     plugin_name=shield
     plugin_version={% if shield_version is defined %}{{ shield_version }}{% endif %}

- include: plugin.yml
     plugin_name=sense
     plugin_version={% if sense_version is defined %}{{ sense_version }}{% endif %}

- include: plugin.yml
     plugin_name=reporting
     plugin_version={% if reporting_version is defined %}{{ reporting_version }}{% endif %}

- name: install key and certificate
  copy: src=files/{{ item }} dest=/opt/kibana/config/{{ item }} mode=0644
  with_items:
    - server.key
    - server.crt

- name: install config file (specific)
  template: src=kibana.yml dest=/opt/kibana/config/kibana.yml mode=0644
  notify:
     - restart kibana

#curl -XPUT -u admin 'http://<host>:<port>/_license?acknowledge=true' -d @license.json

- name: Start kibana services
  service: name=kibana state=started enabled=yes

