---
- name: install logstash
  apt: deb=http://bastion/repos/logstash-{{ logstash_version }}.deb state=present 

- name: install config file (specific)
  template: src=logstash.conf.j2 dest=/etc/logstash/conf.d/logstash.conf mode=0644
  with_items:
    - elasticsearch_hosts: "[{% set comma = joiner(',') %}{% for host in groups['elasticsearch'] %}{{ comma() }}'{{ host }}:{{ es_api_port }}'{% endfor %}]"
  notify:
     - restart logstash

- include: plugin.yml
     plugin_name=logstash-codec-collectd
     plugin_version={% if collectd_version is defined %}{{ collectd_version }}{% endif %}

- name: Start logstash services
  service: name=logstash state=started enabled=yes
